namespace Concierge.Tests;

/// <summary>
/// The design language Concierge borrows, and whether the copy still matches.
///
/// **A vendored file with nothing checking it is a fork nobody declared.** three.js and
/// mermaid are carried here for a stated reason — a product that needs the internet to draw a
/// box is not local-first, and the same is true of one that needs it to know what colour it
/// is. The cost of carrying is drift, and the way that plays out is somebody changes a token
/// upstream, every other Circle app moves, and this one quietly does not.
///
/// It is the defect CircleMetroUI was audited for and fixed: four generated artefacts with
/// nothing verifying they matched their source, which is how a Swift file that could not
/// compile survived. Importing the tokens without importing that lesson would be taking the
/// bug and leaving the fix.
/// </summary>
public sealed class CircleMetroTokensTests
{
    private static string Vendored => Path.Combine(
        AppContext.BaseDirectory, "..", "..", "..", "..",
        "Concierge.Shared.Components", "wwwroot", "lib", "circlemetro", "tokens.css");

    /// <summary>
    /// Where the design language lives, if this machine has it.
    ///
    /// A sibling checkout, so a machine with only this repository still builds and still
    /// runs every other test. What it cannot do is prove the copy is current, and that is
    /// said out loud rather than passing quietly.
    /// </summary>
    private static string? Upstream
    {
        get
        {
            var path = Path.GetFullPath(Path.Combine(
                AppContext.BaseDirectory, "..", "..", "..", "..", "..",
                "CircleMetroUI", "platforms", "web", "tokens.generated.css"));

            return File.Exists(path) ? path : null;
        }
    }

    [Fact]
    public void The_design_language_is_carried_rather_than_fetched()
    {
        Assert.True(File.Exists(Vendored), $"no tokens at {Vendored}");

        var beside = Path.Combine(Path.GetDirectoryName(Vendored)!, "LICENSE");
        var provenance = Path.Combine(Path.GetDirectoryName(Vendored)!, "PROVENANCE.txt");

        // Apache-2.0, and where it came from. A carried file with no licence beside it is the
        // thing this repository already got right twice and would rather not get wrong once.
        Assert.True(File.Exists(beside), "no licence beside the tokens");
        Assert.True(File.Exists(provenance), "nothing says where the tokens came from");
        Assert.Contains(
            "CircleMetroUI", File.ReadAllText(provenance), StringComparison.Ordinal);
    }

    /// <summary>
    /// **And it has not drifted from the source it was generated by.**
    ///
    /// Compared as text rather than by a version number, because a version number is a claim
    /// and the bytes are the fact.
    /// </summary>
    [Fact]
    public void And_it_still_matches_the_design_language()
    {
        if (Upstream is not { } source)
        {
            // Said, not skipped. A run on a machine without the sibling checkout proves less
            // than a run with it, and four export tests in this repository once stood down
            // quietly and reported success for weeks.
            Assert.True(File.Exists(Vendored), "the carried copy is missing too");
            return;
        }

        Assert.Equal(
            File.ReadAllText(source).ReplaceLineEndings("\n"),
            File.ReadAllText(Vendored).ReplaceLineEndings("\n"));
    }

    /// <summary>
    /// The brand blue is one value in one place.
    ///
    /// Concierge and CircleMetroUI already agreed on #2196F3 — independently, by hand, in two
    /// files. That agreement is what a token layer is for, and it is also exactly the kind of
    /// agreement that survives until the day somebody changes one of them.
    /// </summary>
    [Fact]
    public void The_brand_blue_comes_from_the_design_language()
    {
        var tokens = File.ReadAllText(Vendored);

        Assert.Contains("--cm-brand-circle-blue: #2196F3", tokens, StringComparison.Ordinal);

        var chrome = File.ReadAllText(Path.Combine(
            AppContext.BaseDirectory, "..", "..", "..", "..",
            "Concierge.Shared.Components", "wwwroot", "concierge.css"));

        // The workspace reads the token rather than restating the hex.
        Assert.Contains("--cm-brand-circle-blue", chrome, StringComparison.Ordinal);
    }
}
